import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Project-level configuration loaded from `uncle_bob.yaml`.
class UncleBobConfig {
  /// Dart package name from the target project's `pubspec.yaml`.
  final String packageName;

  /// Root folder for generated features (default: `lib/features`).
  final String featuresPath;

  /// Root folder for generated core layers (default: `lib/core`).
  final String corePath;

  /// Relative path to the dependency injection file.
  final String diFile;

  /// Last saved base response JSON reused across feature questionnaires.
  final String lastBaseResponseExample;

  /// Last saved pagination JSON reused across feature questionnaires.
  final String lastPaginationExample;

  /// JSON key used for pagination (`paginationData` or `pagination`).
  final String lastPaginationKey;

  /// Creates a configuration with explicit paths and optional API defaults.
  const UncleBobConfig({
    required this.packageName,
    required this.featuresPath,
    required this.corePath,
    required this.diFile,
    this.lastBaseResponseExample = '',
    this.lastPaginationExample = '',
    this.lastPaginationKey = '',
  });

  /// Default paths used when `uncle_bob.yaml` is missing or incomplete.
  static const defaults = UncleBobConfig(
    packageName: 'my_app',
    featuresPath: 'lib/features',
    corePath: 'lib/core',
    diFile: 'lib/injection_container.dart',
  );

  /// Loads configuration from [file], falling back to [packageName] and [defaults].
  factory UncleBobConfig.fromYamlFile(File file, {required String packageName}) {
    if (!file.existsSync()) {
      return UncleBobConfig(
        packageName: packageName,
        featuresPath: defaults.featuresPath,
        corePath: defaults.corePath,
        diFile: defaults.diFile,
      );
    }

    final yaml = loadYaml(file.readAsStringSync());
    if (yaml is! YamlMap) {
      return UncleBobConfig(
        packageName: packageName,
        featuresPath: defaults.featuresPath,
        corePath: defaults.corePath,
        diFile: defaults.diFile,
      );
    }

    return UncleBobConfig(
      packageName: yaml['package_name']?.toString() ?? packageName,
      featuresPath: yaml['features_path']?.toString() ?? defaults.featuresPath,
      corePath: yaml['core_path']?.toString() ?? defaults.corePath,
      diFile: yaml['di_file']?.toString() ?? defaults.diFile,
      lastBaseResponseExample:
          yaml['last_base_response_example']?.toString() ?? '',
      lastPaginationExample: yaml['last_pagination_example']?.toString() ?? '',
      lastPaginationKey: yaml['last_pagination_key']?.toString() ?? '',
    );
  }

  /// Returns a copy with selectively overridden fields.
  UncleBobConfig copyWith({
    String? packageName,
    String? featuresPath,
    String? corePath,
    String? diFile,
    String? lastBaseResponseExample,
    String? lastPaginationExample,
    String? lastPaginationKey,
  }) {
    return UncleBobConfig(
      packageName: packageName ?? this.packageName,
      featuresPath: featuresPath ?? this.featuresPath,
      corePath: corePath ?? this.corePath,
      diFile: diFile ?? this.diFile,
      lastBaseResponseExample:
          lastBaseResponseExample ?? this.lastBaseResponseExample,
      lastPaginationExample:
          lastPaginationExample ?? this.lastPaginationExample,
      lastPaginationKey: lastPaginationKey ?? this.lastPaginationKey,
    );
  }

  /// Serializes this configuration to YAML for `uncle_bob.yaml`.
  String toYaml() {
    return '''
# Generated by uncle_bob — customize paths for your project.
package_name: $packageName
features_path: $featuresPath
core_path: $corePath
di_file: $diFile
${_yamlBlockIfNotEmpty('last_base_response_example', lastBaseResponseExample)}${_yamlBlockIfNotEmpty('last_pagination_example', lastPaginationExample)}${_yamlScalarIfNotEmpty('last_pagination_key', lastPaginationKey)}
''';
  }

  /// Absolute feature root for [featureSnake] under [featuresPath].
  String featureRoot(String featureSnake) => p.join(featuresPath, featureSnake);
}

String _yamlScalarIfNotEmpty(String key, String value) {
  if (value.trim().isEmpty) return '';
  return '$key: "$value"\n';
}

String _yamlBlockIfNotEmpty(String key, String value) {
  final trimmed = value.trim();
  if (trimmed.isEmpty) return '';
  final indented = trimmed.split('\n').map((line) => '  $line').join('\n');
  return '$key: |\n$indented\n';
}
